#!/bin/sh

exec 2>&1
ulimit -v 512000
export REAL_SCRIPT_NAME=""
exec /home/shish/bin/spawn-fcgi -n -s /tmp/fcgi-cot.sock -u shish -U www-data -d /home/shish/commentonthis.net/htdocs -- ../app/commentonthis.py fastcgi
